name: movies
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  youtube_player_iframe: ^5.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700